apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: community
spec:
  interval: 5m0s
  url: oci://ghcr.io/rawkodeacademy/studio-deploy
  ref:
    tag: latest
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: studio
spec:
  interval: 5m
  targetNamespace: studio
  sourceRef:
    kind: OCIRepository
    name: studio
  path: "./"
  prune: true
  patches:
    - target:
        kind: Kustomization
      patch: |-
        - op: replace
          path: /spec/targetNamespace
          value: studio
